#cloud-config

users:
- name: datadog
  uid: 2000

write_files:
- path: /etc/systemd/system/datadog.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start a datadog agent

    [Service]
    Environment="HOME=/home/datadog"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
    ExecStart=/usr/bin/docker run --net="host" --rm --name=datadog eu.gcr.io/my-registry/es_dd:latest
    ExecStop=/usr/bin/docker stop datadog
    ExecStopPost=/usr/bin/docker rm datadog

runcmd:
- systemctl daemon-reload
- systemctl start datadog.service
